/*
 * File: app/store/rosenStore.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.rosenStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.rosenDataModel'
    ],

    config: {
        autoLoad: true,
        model: 'MyApp.model.rosenDataModel',
        storeId: 'rosenStore',
        proxy: {
            type: 'ajax',
            batchActions: false,
            url: 'http://www.ekidata.jp/api/p/23.xml',
            headers: [
                {
                    'Access-Control-Allow-Origin': '*'
                }
            ],
            useDefaultXhrHeader: false,
            reader: {
                type: 'xml',
                record: 'line'
            }
        }
    }
});