/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.Panel',

    config: {
        ui: 'light',
        items: [
            {
                xtype: 'fieldset',
                disabled: false,
                title: '沿線',
                items: [
                    {
                        xtype: 'numberfield',
                        label: 'Field'
                    },
                    {
                        xtype: 'datepickerfield',
                        label: 'Field',
                        placeHolder: 'yyyy-mm-dd',
                        picker: {
                            useTitles: true,
                            dayText: '日',
                            monthText: '月',
                            slotOrder: [
                                'year',
                                'month',
                                'day'
                            ],
                            yearText: '年'
                        }
                    }
                ]
            },
            {
                xtype: 'picker',
                slots: [
                    {
                        xtype: 'pickerslot',
                        data: [
                            {
                                text: 'One',
                                value: 1
                            },
                            {
                                text: 'Two',
                                value: 2
                            },
                            {
                                text: 'Three',
                                value: 3
                            }
                        ],
                        name: 'MyPickerSlot',
                        title: 'MyPickerSlot'
                    }
                ]
            }
        ]
    }

});